services:
  descartes:
    build:
      context: .
      args:
          BASE_IMAGE: jupyter/base-notebook
    command: sh -c "jupyter lab --allow-root --no-browser --ip=0.0.0.0"
    volumes:
      - ./software-engineer-technical-test:/thomas/software-engineer-technical-test
    ports:
      - "8888:8888"
      - "6006:6006"
    privileged: true


